NervJS/taro-ui

docs/markdown/grid.md

修复 `Grid` 组件 。`mode`、`hasBorder `参数的错误描述及错误的默认值。

docs(grid): 修改文档错误

---

@types/textarea.d.ts
docs/markdown/input.md

fixed typo

---

@types/button.d.ts

Button控件的事件函数定义错误，在用typescript开发时会提示类型问题。

fix(button.d.ts):事件函数类型错误修改

---

docs/markdown/accordion.md

docs: 更新文档

---

@types/input-number.d.ts
docs/markdown/input-number.md
src/components/input-number/index.js

https://github.com/NervJS/taro-ui/issues/394
为AtInputNumber添加错误提示回调

feat(AtInputNumber): 为AtInputNumber添加错误提示回调

---

src/components/input-number/index.js

fix(input-number): 修改错误的小驼峰写法

---

docs/markdown/action-sheet.md

Replace Chinese single quotes with English single quotes.

docs(action-sheet): 完善文档

---

docs/markdown/quickstart.md

Fix quickstart.md

---

docs/markdown/curtain.md
src/pages/view/curtain/index.js

完善 Curtain 关闭图标位置的示例和文档

---

docs/markdown/swiper.md

swiper.md修改错别字

---

@types/textarea.d.ts

修改 textarea.d.ts 类型声明不正确

---

src/components/countdown/index.js
src/pages/view/countdown/index.js

fix(countdown): 修复了不显示天数时hours传入的值大于23显示有误的问题

---

docs/markdown/accordion.md
src/components/accordion/index.js
src/components/accordion/index.test.js

图标，增加对支持 AtIcon 支持的类型中，prefixClass 属性的支持

增加 Accordion 手风琴组件的图标对 prefixClass 属性支持

---

@types/input.d.ts

https://github.com/NervJS/taro-ui/issues/644

fix type InputFunction bugs

---

docs/markdown/list.md

list组件文档描述错误

---

src/components/fab/__snapshots__/index.test.js.snap
src/components/fab/index.js
src/components/fab/index.test.js

fix(fab): add className props for AtFab, fixes #850

---

docs/markdown/calendar.md

增加日历组件有效时间组（validDates）的参数说明与demo

docs(calendar): 增加日历组件有效时间组的使用说明

---

src/style/components/tab-bar.scss

feat(tabBar): 增加了 tabBar 的paddingBottom

---

src/components/input-number/index.tsx

增加非法数值校验：
禁止输入数值以外；
禁止输入多个小数点；
输入非法字符后截取数值部分；

fix: input-number 组件：在微信小程序中可以输入非数字或者不合法数字 #985

---

packages/taro-ui/src/components/input/index.tsx

fix: input props maxlength

---

src/components/progress/index.tsx

**修改点**： 将 backgroundColor 属性改为 background
**原因**： backgroundColor 设置颜色时不支持渐变色，而 background 支持，自由度更大

fix(Process): use background attr instead of backgroundColor

---

src/components/swipe-action/options/index.tsx

将 `swipe-action` -> `option` 组件的 `trrigerOptionsDomUpadte` 修改为 `triggerOptionsDomUpdate`

fix(swipe-action): 修复function名称

---

src/components/modal/index.tsx

`componentWillReceiveProps` 在特定情况下会有不生效的问题，改用`static getDerivedStateFromProps`

feat(Modal): 修改Modal Props修改后不生效的问题

---

packages/taro-ui/src/components/calendar/common/helper.ts
packages/taro-ui/src/components/calendar/ui/date-list/index.tsx

https://github.com/NervJS/taro-ui/issues/1125
修复日历组件marks参数失效

修复日历组件marks参数失效

---

src/components/calendar/ui/date-list/index.tsx

删除无用的文本内容
[#1038](https://github.com/NervJS/taro-ui/issues/1038#issue-607971184)

fix(calendar): remove useless text

---

docs/markdown/float-layout.md
docs/markdown/indexes.md
package.json
src/components/float-layout/index.tsx
src/components/indexes/index.tsx
src/pages/navigation/indexes/mock-data.ts
types/float-layout.d.ts
types/indexes.d.ts

Float-Layout 组件新增 closeOnClickOverlay 属性，让开发者自己根据应用场景自己可以配置。

Float-Layout 组件新增 closeOnClickOverlay 属性
